PoraoDosInstrumentos/PoraoDosInstrumentos/Models/Anuncio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PoraoDosInstrumentos.Models
{
    public class Anuncio
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Seu produto deve ter um Titulo!")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "Seu produto deve ter uma Descrição!")]
        public string Descricao { get; set; }
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Range(0, 500)]
        public decimal Valor { get; set; }
        public string usuario { get; set; }
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        [Display(Name = "Upload image")]
        public byte[] ImageFile { get; set; }
        public string ImageMimeType { get; set; }
        [Display(Name = "Image link")]
        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }
        public int CategoriaID { get; set; }
        public virtual Categoria Categoria { get; set; }
        public int LocalID { get; set; }
        public virtual Local Local { get; set; }
        public int VendedorID { get; set; }
        public virtual Vendedor Vendedor { get; set; }

        public int StatusItemID{ get; set; }
        public virtual StatusItem StatusItem { get; set; }
    }
}

PoraoDosInstrumentos/PoraoDosInstrumentos/Controllers/AnuncioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoraoDosInstrumentos.Models;

namespace PoraoDosInstrumentos.Controllers
{
    public class AnuncioController : Controller
    {
        private AnuncioDBContext db = new AnuncioDBContext();

        public ActionResult Index(string searchString, string sortOrder, int? SelectedCategoria)
        {
            var anuncios = db.Anuncios.Include(a => a.Categoria).Include(a => a.Local).Include(a => a.Vendedor);

            if (!String.IsNullOrEmpty(searchString))
            {
                anuncios = anuncios.Where(s => s.Titulo.Contains(searchString) || s.Descricao.Contains(searchString));
            }

            ViewBag.ValorSortParm = sortOrder == "Valor" ? "valor_asc" : "Valor";

            switch (sortOrder)
            {
                case "Valor":
                    anuncios = anuncios.OrderByDescending(s => s.Valor);
                    break;
                case "rating_asc":
                    anuncios = anuncios.OrderBy(s => s.Valor);
                    break;
            }
            return View(anuncios.ToList());
        }
        public ActionResult AnuncioFilter(string term)
        {
            term = term.ToLower();
            var anuncios = from Anuncio in db.Anuncios
                           where (Anuncio.Titulo.ToLower().Contains(term))
                           select Anuncio.Titulo; return Json(anuncios, JsonRequestBehavior.AllowGet);
        }

        // GET: Anuncio/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anuncio anuncio = db.Anuncios.Find(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            return View(anuncio);
        }

        // GET: Anuncio/Comprar/5
        public ActionResult Comprar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anuncio anuncio = db.Anuncios.Find(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            return View(anuncio);
        }
        [Authorize]
        public ActionResult Send(String message)
        {
            string emailTo = User.Identity.Name;

            SendEmail.CreateMailMessage(emailTo, "nova mensagem", message);
            return View();
        }

        // retorna a imagem associada a um produto
        public ActionResult GetImage(int id)
        {
            Anuncio anuncio = db.Anuncios.Find(id);
            if (anuncio != null && anuncio.ImageFile != null)
            {
                //File used to return a binary content and the contenttype of the returned photo
                return File(anuncio.ImageFile, anuncio.ImageMimeType);
            }
            else
            {
                return new FilePathResult("~/Images/nao-disponivel.jpg", "image/jpeg");
            }
        }

        // GET: Anuncio/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome");
            ViewBag.LocalID = new SelectList(db.Locais, "LocalID", "Nome");
            ViewBag.VendedorID = new SelectList(db.Vendedores, "VendedorID", "ImageUrl");
            ViewBag.StatusItemID = new SelectList(db.StatusItems, "StatusItemID", "status");



            return View();
        }

        // POST: Anuncio/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titulo,Descricao,Valor,ReleaseDate,ImageUrl,CategoriaID,LocalID,VendedorID,StatusItemID")] Anuncio anuncio,
                             HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                //if image object is not empty update the photo attribute, using image info.
                if (image != null)
                {
                    anuncio.ImageMimeType = image.ContentType;
                    anuncio.ImageFile = new byte[image.ContentLength];
                    //save the photo file by using image.InputStream.Read method.
                    image.InputStream.Read(anuncio.ImageFile, 0, image.ContentLength);
                }

                anuncio.usuario = User.Identity.Name;
                anuncio.StatusItemID = 1;
                db.Anuncios.Add(anuncio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", anuncio.CategoriaID);
            ViewBag.LocalID = new SelectList(db.Locais, "LocalID", "Nome", anuncio.LocalID);
            ViewBag.VendedorID = new SelectList(db.Vendedores, "VendedorID", "ImageUrl", anuncio.VendedorID);
            ViewBag.StatusItemID = new SelectList(db.StatusItems, "StatusItemID", "status", anuncio.StatusItemID);

            return View(anuncio);
        }

        // GET: Anuncio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anuncio anuncio = db.Anuncios.Find(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            ViewBag.StatusItemID = new SelectList(db.StatusItems, "StatusItemID", "status", anuncio.StatusItemID);
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", anuncio.CategoriaID);
            ViewBag.LocalID = new SelectList(db.Locais, "LocalID", "Nome", anuncio.LocalID);
            ViewBag.VendedorID = new SelectList(db.Vendedores, "VendedorID", "ImageUrl", anuncio.VendedorID);
            return View(anuncio);
        }

        // POST: Anuncio/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,Descricao,Valor,ReleaseDate,ImageUrl,CategoriaID,LocalID,VendedorID,StatusItemID")] Anuncio anuncio,
                                HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                //if image object is not empty update the photo attribute, using image info.
                if (image != null)
                {
                    anuncio.ImageMimeType = image.ContentType;
                    anuncio.ImageFile = new byte[image.ContentLength];
                    //save the photo file by using image.InputStream.Read method.
                    image.InputStream.Read(anuncio.ImageFile, 0, image.ContentLength);
                }
                anuncio.usuario = User.Identity.Name;
                anuncio.VendedorID = 1;
                db.Entry(anuncio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", anuncio.CategoriaID);
            ViewBag.LocalID = new SelectList(db.Locais, "LocalID", "Nome", anuncio.LocalID);
            ViewBag.VendedorID = new SelectList(db.Vendedores, "VendedorID", "ImageUrl", anuncio.VendedorID);
            ViewBag.StatusItemID = new SelectList(db.StatusItems, "StatusItemID", "status", anuncio.StatusItemID);
            return View(anuncio);
        }

        // GET: Anuncio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anuncio anuncio = db.Anuncios.Find(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            return View(anuncio);
        }

        // POST: Anuncio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Anuncio anuncio = db.Anuncios.Find(id);
            db.Anuncios.Remove(anuncio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: /Anuncio/CategoriaMenu 
        [ChildActionOnly]
        public ActionResult CategoriaMenu(int num = 5)
        {
            var categorias = db.Categorias.
                OrderByDescending(c => c.Anuncios.Count)
                .Take(num)
                .ToList();
            return this.PartialView(categorias);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PoraoDosInstrumentos/PoraoDosInstrumentos/Views/Anuncio/Comprar.cshtml
@model PoraoDosInstrumentos.Models.Anuncio

@{
    ViewBag.Title = "Comprar";
}

<h2>Comprar</h2>

<div>
    <h4>Anuncio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Local.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Local.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vendedor.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vendedor.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PoraoDosInstrumentos/PoraoDosInstrumentos/Views/Anuncio/Create.cshtml
@model PoraoDosInstrumentos.Models.Anuncio

@{
    ViewBag.Title = "Create";
}

<h2>Cadastrar Produto</h2>

@using (Html.BeginForm("Create", "Anuncio", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Anuncio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, "Data", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaID, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalID, "Local", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocalID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="visibility: hidden">
            @Html.LabelFor(model => model.VendedorID, "Vendedor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VendedorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PoraoDosInstrumentos/PoraoDosInstrumentos/Views/Anuncio/Delete.cshtml
@model PoraoDosInstrumentos.Models.Anuncio

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir Anuncio:</h2>
<div class="alert alert-warning">
    <strong>Atencão!</strong> Deseja excluir seu anuncio?
</div>
<div>
    <h4>Anuncio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Categoria Tipo:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            Cidade:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Local.Nome)
        </dd>

        <dt>
            E-mail do Anunciante:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vendedor.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            Data do Anuncio:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            Imagem Produto:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
            @if (Model.ImageUrl != null)
            {
                <img width="340" src="@Model.ImageUrl" alt=@Model.Titulo>
            }
            else
            {
                <img width="200" src="@Url.Action("GetImage", "Anuncio", new { id=Model.ID})" />
            }
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="container">
            <!-- Trigger the modal with a button -->
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Deletar</button>


            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">ATENÇÃO:</h4>
                        </div>
                        <div class="modal-body">
                            <div class="container">
                                <h2>Remover Anúncio!</h2>
                                <div class="alert alert-danger col-lg-3">
                                    <strong>Atenção! </strong> Excluir definitivamente?
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="col-lg-2">
                                <input type="submit" value="Excluir" class="btn btn-danger" />
                            </div>
                            <div class="col-lg-4">
                                <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <br />
            <div>
                @Html.ActionLink(" << Voltar p/ Anuncios", "Index")
            </div>
    }
</div>

PoraoDosInstrumentos/PoraoDosInstrumentos/Views/Anuncio/Details.cshtml
@model PoraoDosInstrumentos.Models.Anuncio

@{
    ViewBag.Title = "Details";
}



<h2>Detalhes</h2>

<div>
    <h4>Anuncio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p class="bg-primary">Tipo de Produto:</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            <p class="bg-primary">Cidade:</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Local.Nome)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Vendedor.ImageUrl)
        </dd>
        <dt>
            <p class="bg-primary">Titulo:</p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            <p class="bg-primary">descrição:</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            <p class="bg-primary">Valor do produto:</p>
        </dt>


        <dt>
            <p class="bg-primary">Status:</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusItem.status)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            <p class="bg-primary">Data do cadastro:</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            <p class="bg-primary">E-mail Vendedor:</p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>
        <dt>
            <p class="bg-primary">Imagem Produto:</p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
            @if (Model.ImageUrl != null)
            {
                <img width="340" height="240" src="@Model.ImageUrl" alt=@Model.Titulo class="img-thumbnail">
            }
            else
            {
                <img width="340" height="240" src="@Url.Action("GetImage", "Anuncio", new { id=Model.ID})" class="img-thumbnail" />
            }
        </dd>
    </dl>
</div>
<div class="container">
    <h2>Avaliação do vendedor:</h2>
    <div class="stars-default" data-rating="3"><input type="hidden" id="stars" name="rating" /></div>
</div>
<br />

<p>
    @if ((User.Identity.Name == "admin@s2b.br") || (User.Identity.Name == Model.usuario))
    {
        @Html.ActionLink(" ", "Delete", new { id = Model.ID }, new { @class = "btn btn-danger deleteBtn  btn-xs glyphicon glyphicon-trash" })
    } |
    @if (User.Identity.Name == Model.usuario)
    {
        @Html.ActionLink("Editar", "Edit", new { id = Model.ID }, new { @class = "btn btn-warning" })
    } |
    @if (User.Identity.Name == Model.usuario)
    {
        @Html.ActionLink("Comprar", "Comprar", new { id = Model.ID }, new { @class = "btn btn-primary disabled" })
    }
    else
    {
        @Html.ActionLink("Comprar", "Comprar", new { id = Model.ID }, new { @class = "btn btn-primary" })
    } |

    @Html.ActionLink("Voltar Para Anuncios", "Index")
</p>

@section scripts{
    @Scripts.Render("~/Scripts/rating.js")

}

PoraoDosInstrumentos/PoraoDosInstrumentos/Views/Anuncio/Edit.cshtml
@model PoraoDosInstrumentos.Models.Anuncio

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Anuncio", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Anuncio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, "Data:",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, "Imagem:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaID, "Categoria:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalID, "Cidade:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocalID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusItemID, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusItemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusItemID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group hidden">
            @Html.LabelFor(model => model.VendedorID, "VendedorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VendedorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VendedorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Anuncios", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}